baseURL = "http://raptorz.github.io/"
languageCode = "en-us"
title = "raptor's chinglish blog"
author = "raptorz"
theme = "code-editor"
copyright = "Copyright (c) 2014 - 2018, raptorz; all rights reserved."
canonifyurls = true
paginate = 3

[params]
    author = "raptorz"
    locale = "en-US"
    # rootlink = "/"
    # rootlink specifies where Root in menu.html links to. If it's not set then baseurl will be used.
