baseURL = "http://raptorz.github.io/"
languageCode = "en-us"
title = "raptor's chinglish blog"
author = "raptorz"
theme = "bootstrap"
copyright = "Copyright (c) 2014 - 2018, raptorz; all rights reserved."
canonifyurls = true
paginate = 3
